Apoorv-cloud/1_Hacktoberfest-22

index.html

Add the playlist

---

index.html

Added my playlist Chill Mood

---

index.html

New playlist

---

index.html
style.css

Add Main Display Section

---

index.html

Anchal added a playlist

---

index.html
index.js
style.css

Changes made:
1. Added a new playlist by the name of "Indie Playlist"
2. Added the script tag to link the js file "index.js"
3. Added a new button to go to the top of the page from anywhere.
4. Wrote the necessary javascript and the css for the button.

Updated the files index.js, index.html and styles.css

---

index.html

playlist by Harsh Tripathi added

new playlist added

---

index.html

4th_playlist

---

index.html

1. [x] Added my playlist card named "DARK EUPHORIA".

Added my playlist

---

index.html

2nd playlist

---

index.html

New playlist by diosa imperfecta added.

Playlist added

---

index.html

Added Deepak Jain's card

---

index.html

Added the playlist Link.
Kartikey Tandon - BRL Trainee

Kartikey's Playlist

---

.hintrc
index.html

Harsh Dhama's Playlist

---

index.html

First Playlist Added

---

index.html

myplaylist

---

index.html

added playlists again

---

index.html

Add a playlist

---

index.html

I have added my own spotify playlist.

I have added my spotify playlist

---

index.html

i have added my own spotify playlist..

hello..i have added my spotify playlist

---

index.html

PetrolHead playlist added

---

index.html

EFT playlist added.

---

index.html

i have a new punjabi playlist .

added playlist

---

index.html

updated cover image for my playlist

---

index.html

Added another playlist to the BRL playlists

Added another playlist

---

index.html

My first Playlist - Prajwal

---

index.html

Created card

---

index.html

Newbranch1

---

index.html

brl trainee 
updated playlist added

newplaylist

---

index.html

I have added an emotional songs .

song playlist

---

index.html

Updated fork

---

index.html

4th commit

---

index.html

i have added my third playlist

added third playlist 

---

index.html

Third Playlist Added

---

index.html

HARSH DHAMA NEW PLAYLIST BRL MEMBER

Brlnewplaylist

---

index.html

added my spotify card

---

index.html

updated the cover image of my playlist

---

index.html

First Playlist added.

---

index.html

Transformers Playlist Added

---

index.html

Submission of Samrat Srivastava (BRL Trainee)

Fourth playlist added

---

index.html

Linkin Park Playlist Added
